GET http://localhost:5000/private HTTP/1.1
HEAD 
x-access-tokens: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiI3NGNkOGYxMC0zNDU3LTQwYmYtYTc2NS1iMTQ4YjEzMDIwNGMiLCJpYXQiOjE1ODk2ODMxMTYsImV4cCI6MTU4OTcwNDcxNn0.zwjhRHiVDkv_zJJhxI9DWCz71-w_10vi075Y0F9w6IA

###
POST http://localhost:5000/api/refresh-token HTTP/1.1
HEAD 
x-access-tokens: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiI3NGNkOGYxMC0zNDU3LTQwYmYtYTc2NS1iMTQ4YjEzMDIwNGMiLCJpYXQiOjE1ODk2ODMxMTYsImV4cCI6MTU4OTcwNDcxNn0.zwjhRHiVDkv_zJJhxI9DWCz71-w_10vi075Y0F9w6IA

###

POST http://localhost:5000/api/login HTTP/1.1
content-type: application/json

{
	"email": "test@gmail.com", 
	"password": "passwordsicura"
}

###
POST http://localhost:5000/api/register HTTP/1.1
content-type: application/json

{
	"email": "test1@gmail.com", 
	"password": "passwordsicura",
	"username": "user1234"
}