GET http://localhost:8000/private HTTP/1.1
HEAD 
x-access-tokens: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiIwNTZiNDA0Zi03N2Q2LTQ4OTItYmEyMC0wYTFiOTY5ZjhhMzEiLCJ1c2VybmFtZSI6Im1hbnVlbGFydG8iLCJleHAiOjE1ODk2Njk1MjR9.INuLKuEMqDJaJtG_lOde9Oj0vm0_fGtOsumq8td9ibI

###

POST http://localhost:8000/api/login HTTP/1.1
content-type: application/json

{
	"email": "test@gmail.com", 
	"password": "passwordsicura"
}

###
POST http://localhost:8000/api/register HTTP/1.1
content-type: application/json

{
	"email": "test1@gmail.com", 
	"password": "passwordsicura",
	"username": "user1234"
}