### LOCAL

GET http://localhost:5000/private HTTP/1.1
HEAD 
x-access-tokens: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiI2OWY0NTc2ZS1lYTcxLTRmMDAtOTY0Mi04YjdkYzdhZGMxYzMiLCJ1c2VybmFtZSI6ImRldmljZXRlc3QiLCJpYXQiOjE1ODk5MDU5NDgsImV4cCI6MTU4OTkwNzc0OH0.xdGQtJQS7rY3_lFIBGUKC1R8aPaqwPaWKy2Hw41CGaM

###
POST http://localhost:5000/api/refresh-token HTTP/1.1
HEAD 
x-access-tokens: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiI3NGNkOGYxMC0zNDU3LTQwYmYtYTc2NS1iMTQ4YjEzMDIwNGMiLCJpYXQiOjE1ODk3MzMwODEsImV4cCI6MTU4OTczMzE0MX0.DzGGnQWmajsAK-xsZeCRRlPJ0174HhxtnwarFQPeB54

###

POST http://localhost:5000/api/login HTTP/1.1
content-type: application/json

{
	"email": "web@test.com", 
	"password": "ciaociao"
}

###
POST http://localhost:5000/api/register HTTP/1.1
content-type: application/json

{
	"email": "test2@gmail.com", 
	"password": "passwordsicura",
	"username": "user2"
}

###	PRODUCTION

GET https://live-chat-fp.herokuapp.com/private HTTP/1.1
HEAD 
x-access-tokens: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiJjZGM3YjVmMS1kMmVlLTQ3NzctYjgzZS01M2U4YzMyZWViNTkiLCJ1c2VybmFtZSI6InVzZXIxMjM0IiwiaWF0IjoxNTg5NzA3MjAwLCJleHAiOjE1ODk3MDkwMDB9.R77BmyeeB1kaKD6phRBzl_8Q7dRzl3R20jMdw1dv87A

###
POST https://live-chat-fp.herokuapp.com/api/refresh-token HTTP/1.1
HEAD 
x-access-tokens: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiI3NGNkOGYxMC0zNDU3LTQwYmYtYTc2NS1iMTQ4YjEzMDIwNGMiLCJpYXQiOjE1ODk2ODMxMTYsImV4cCI6MTU4OTcwNDcxNn0.zwjhRHiVDkv_zJJhxI9DWCz71-w_10vi075Y0F9w6IA

###

POST https://live-chat-fp.herokuapp.com/api/login HTTP/1.1
content-type: application/json

{
	"email": "test1@gmail.com", 
	"password": "passwordsicura"
}

###
POST https://live-chat-fp.herokuapp.com/api/register HTTP/1.1
content-type: application/json

{
	"email": "device@test.com", 
	"password": "ciaociao",
	"username": "devicetest"
}